export const siteCopy = {
  en: {
    brand: "Dagegme",
    nav: [
      { label: "How It Works", href: "/#how-it-works" },
      { label: "Professionals", href: "/professionals" },
    ],
    languageLabel: "Language",
    themeLabel: "Theme",
    light: "Light",
    dark: "Dark",
    wishlist: "Wishlist",
    wishlistTitle: "Your wishlist",
    wishlistEmpty:
      "Your wishlist is empty. Save professionals you like using the heart icon.",
    removeFromWishlist: "Remove",
    viewListing: "View",
    close: "Close",
    listingDetails: {
      close: "Close details",
      descriptionFallback: "More details will be added soon.",
      save: "Add to wishlist",
      saved: "Saved to wishlist",
      link: "Showreel {number}",
      gallery: "Gallery",
      openImage: "Open gallery image {number}",
      expandImage: "Expand selected photo",
      closeGallery: "Close expanded gallery",
      previousPhoto: "Previous photo",
      nextPhoto: "Next photo",
    },
    heroTitleTop: "Plan your ideal",
    heroTitleAccent: "celebration with ease",
    heroText:
      "Find a photographer, videographer, band, and other professionals for your event.",
    processTitle: "How it works",
    processSteps: [
      { icon: "search", title: "Choose a category" },
      { icon: "shortlist", title: "Find professionals and make your choice" },
      { icon: "chat", title: "Contact us and book +995 555 50 00 19" },
      { icon: "celebrate", title: "Enjoy your event" },
    ],
    about: {
      eyebrow: "About Dagegme",
      title: "One platform — for all your plans",
      text: "Book the service you want easily and quickly.",
      statement: "Every important date begins with stress-free planning.",
      values: [
        {
          icon: "calendar",
          title: "For every important event",
          text: "Find the services you need for a wedding, birthday, corporate event, or any other important occasion.",
        },
        {
          icon: "people",
          title: "A wide range of services",
          text: "Videographers, photographers, bands, DJ, presenters, podcast recording, and photo shoots.",
        },
        {
          icon: "car",
          title: "Car rental",
          text: "Rent a car for your celebration quickly and easily through the same platform.",
        },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Contact us to plan your celebration",
    },
    footer: {
      tagline:
        "One place where every idea becomes reality, simply and quickly. Find and book everything you need for your perfect day.",
      navigationLabel: "Explore",
      links: [
        { label: "Categories", href: "/#categories" },
        { label: "How it works", href: "/#how-it-works" },
        { label: "About us", href: "/#about" },
      ],
      calloutTitle: "Your celebration starts here",
      calloutText:
        "Find the professionals you want and save all your favorites.",
      calloutAction: "View categories",
      note: "Created for unforgettable moments.",
    },
    professionals: {
      eyebrow: "Discover our space",
      title: "Everything you need, all in one place",
      text: "Browse all professionals and services by category. Swipe through the collections, save your favorites, and create the celebration you want.",
      loading: "Loading professionals...",
      error:
        "We could not load the professionals right now. Please try again shortly.",
      categoryTitles: {
        photographers: "Photographers",
        videographers: "Videographers",
        bands: "Bands",
        djs: "DJ",
        presenters: "Presenters",
        studios: "Studios",
        "rental-cars": "Rental cars",
      },
      categoryPage: {
        back: "All professionals",
        subtitle: "Browse every option and save your favorites.",
        results: "{count} results",
        empty: "No professionals have been found yet.",
      },
    },
  },
  ka: {
    brand: "Dagegme",
    nav: [
      { label: "როგორ მუშაობს", href: "/#how-it-works" },
      { label: "პროფესიონალები", href: "/professionals" },
    ],
    languageLabel: "ენა",
    themeLabel: "თემა",
    light: "თეთრი",
    dark: "მუქი",
    wishlist: "სურვილების სია",
    wishlistTitle: "შენი სურვილების სია",
    wishlistEmpty:
      "სურვილების სია ცარიელია. სასურველი პროფესიონალები გულის ნიშნით შეინახე.",
    removeFromWishlist: "წაშლა",
    viewListing: "ნახვა",
    close: "დახურვა",
    listingDetails: {
      close: "დეტალების დახურვა",
      descriptionFallback: "დეტალები მალე დაემატება.",
      save: "სურვილების სიაში დამატება",
      saved: "შენახულია სურვილების სიაში",
      link: "საიმიჯო კლიპი {number}",
      gallery: "გალერეა",
      openImage: "გალერეის სურათის გახსნა {number}",
      expandImage: "არჩეული ფოტოს გადიდება",
      closeGallery: "გადიდებული გალერეის დახურვა",
      previousPhoto: "წინა ფოტო",
      nextPhoto: "შემდეგი ფოტო",
    },
    heroTitleTop: "დაგეგმე იდეალური",
    heroTitleAccent: "დღესასწაული მარტივად",
    heroText:
      "იპოვე ფოტოგრაფი, ვიდეოგრაფი, ბენდი და სხვა პროფესიონალები შენი ღონისძიებისთვის.",
    processTitle: "როგორ მუშაობს",
    processSteps: [
      { icon: "search", title: "აირჩიე კატეგორია" },
      { icon: "shortlist", title: "მოიძიე პროფესიონალები და აარჩიე" },
      { icon: "chat", title: "დაგვიკავშირდი და დაჯავშნე +995 555 50 00 19" },
      { icon: "celebrate", title: "ისიამოვნე ღონისძიებით" },
    ],
    about: {
      eyebrow: "დაგეგმეს შესახებ",
      title: "ერთი პლატფორმა — ყველა შენი გეგმისთვის",
      text: "დაჯავშნე შენთვის სასურველი მომსახურება მარტივად და სწრაფად.",
      statement: "მნიშვნელოვანი თარიღი მშვიდი დაგეგმვით იწყება.",
      values: [
        {
          icon: "calendar",
          title: "ყველა მნიშვნელოვანი ღონისძიებისთვის",
          text: "იპოვე ქორწილისთვის, დაბადების დღისთვის, კორპორატიული თუ სხვა მნიშვნელოვანი ღონისძიებისთვის საჭირო სერვისები.",
        },
        {
          icon: "people",
          title: "მომსახურების ფართო არჩევანი",
          text: "ვიდეოგრაფები, ფოტოგრაფები, ბენდები, DJ-ები, წამყვანები, პოდკასტების ჩაწერა და ფოტოსესიები.",
        },
        {
          icon: "car",
          title: "ავტომობილის დაქირავება",
          text: "ამავე პლატფორმიდან სწრაფად და მარტივად იქირავე ავტომობილი შენი დღესასწაულისთვის.",
        },
      ],
    },
    contact: {
      eyebrow: "კონტაქტი",
      title: "დაგვიკავშირდით თქვენი დღესასწაულის დასაგეგმად",
    },
    footer: {
      tagline:
        "ერთი სივრცე, სადაც ყველა იდეა რეალობად იქცევა მარტივად და სწრაფად. იპოვე და დაჯავშნე ყველაფერი რაც შენი იდეალური დღისთვის გჭირდება.",
      navigationLabel: "აღმოაჩინე",
      links: [
        { label: "კატეგორიები", href: "/#categories" },
        { label: "როგორ მუშაობს", href: "/#how-it-works" },
        { label: "ჩვენ შესახებ", href: "/#about" },
      ],
      calloutTitle: "შენი დღესასწაული აქ იწყება",
      calloutText: "იპოვე სასურველი პროფესიონალები და შეინახე ყველა რჩეული.",
      calloutAction: "ნახე კატეგორიები",
      note: "შექმნილი დაუვიწყარი მომენტებისთვის.",
    },
    professionals: {
      eyebrow: "აღმოაჩინე ჩვენი სივრცე",
      title: "ყველაფერი, რაც გჭირდება, ერთ სივრცეში",
      text: "დაათვალიერე ყველა პროფესიონალი და მომსახურება კატეგორიების მიხედვით. გადაფურცლე კოლექციები, შეინახე რჩეულები და შექმენი შენთვის სასურველი დღესასწაული.",
      loading: "პროფესიონალები იტვირთება...",
      error:
        "პროფესიონალების ჩატვირთვა ვერ მოხერხდა. გთხოვ, სცადო მოგვიანებით.",
      categoryTitles: {
        photographers: "ფოტოგრაფები",
        videographers: "ვიდეოგრაფები",
        bands: "ბენდები",
        djs: "DJ",
        presenters: "წამყვანები",
        studios: "სტუდიები",
        "rental-cars": "გასაქირავებელი მანქანები",
      },
      categoryPage: {
        back: "ყველა პროფესიონალი",
        subtitle: "დაათვალიერე ყველა ვარიანტი და შეინახე რჩეულები.",
        results: "{count} შედეგი",
        empty: "პროფესიონალები ჯერ არ მოიძებნა.",
      },
    },
  },
};
